print("Hello , Git !")
print("I am learning Git and Github.")
print("I am ready for my practical evalutaion")
print("Data validation started")
print("I am learning git pull and git fetch")
print("Data validation feature added")
print("Data quality check started")
print("Message from feature A")
print("Message from feature A")
print("Message from feature B")
